### ISSUE TITLE
Running sml program

### ISSUE THREAD

**Issue by FishYYW** [Jakehp/language-sml#9]
I am a learner of both sml and atom, but I found nowhere to run my sml program in a repl just as what I did in emacs.

**Comment by JakeHP** [comment]
To run your SML program you'll need a compiler. This plugin just provides syntax highlighting in  Atom.

Check out https://www.smlnj.org

**Comment by FishYYW** [comment]
That reminds me of a seemingly obvious problem! Thanks a lot！
# For Other Novice
- Find a compiler like smlnj
- Maybe you'd like to install a terminal package instead of switching to system bash back and forth
- Add PATH to the sml

**Comment by JakeHP** [comment]
no problem 👍
